# Generated by Django 3.0.6 on 2020-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_dailylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.TextField(),
        ),
    ]
